version: '3'

services:
  react-btc:
    build:
      context: ../react-btc
    ports:
      - "8000:8000"
    volumes:
      - ../react-btc:/app

  nest-simple-api:
    build:
      context: ../nest-simple-api
    ports:
      - "3000:3000"
    volumes:
      - ../nest-simple-api:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
